import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import Navbar from '../../components/Navbar';
import Footer from '../../components/Footer';
import SEOHead from '../../components/SEOHead';
import API_BASE_URL from '../../utils/api';
import AdBanner from '../../components/AdBanner';

const AuthorityChecker = () => {
    const [url, setUrl] = useState('');
    const [loading, setLoading] = useState(false);
    const [copied, setCopied] = useState(false);
    const [result, setResult] = useState(null);

    const handleCheck = async (e) => {
        e.preventDefault();
        if (!url.trim()) return;
        setLoading(true);
        try {
            const res = await fetch(`${API_BASE_URL}/api/authority?url=${encodeURIComponent(url)}`);
            const data = await res.json();
            setResult(data);
        } catch (error) {
            console.error(error);
            alert("Failed to check authority.");
        } finally {
            setLoading(false);
        }
    };

    const handleCopyReport = () => {
        if (!result) return;
        const text = `🛡️ AUTHORITY REPORT: ${result.url}\n\n` +
            `Domain Rating:  ${result.domainRating}/100\n` +
            `Page Authority: ${result.pageAuthority}/100\n` +
            `Spam Score:     ${result.spamScore}\n\n` +
            `── METRICS ──\n` +
            `Backlinks: ${result.backlinksCount?.toLocaleString()}\n` +
            `Referring Domains: ${result.referringDomains?.toLocaleString()}\n\n` +
            `Generated by Flamerscoal Authority Intelligence`;
        navigator.clipboard.writeText(text);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    const ScoreRing = ({ score, label, color }) => {
        const r = 40;
        const circ = 2 * Math.PI * r;
        const offset = circ - (score / 100) * circ;
        return (
            <div className="flex flex-col items-center">
                <div className="relative flex items-center justify-center w-24 h-24 mb-4">
                    <svg className="w-full h-full -rotate-90">
                        <circle cx="48" cy="48" r={r} fill="none" stroke="rgba(255,255,255,0.05)" strokeWidth="8" />
                        <motion.circle
                            cx="48" cy="48" r={r} fill="none"
                            stroke={color} strokeWidth="8"
                            strokeLinecap="round"
                            strokeDasharray={circ}
                            initial={{ strokeDashoffset: circ }}
                            animate={{ strokeDashoffset: offset }}
                            transition={{ duration: 1.5, ease: "easeOut" }}
                        />
                    </svg>
                    <span className="absolute text-2xl font-black text-white">{score}</span>
                </div>
                <p className="text-[10px] font-black uppercase tracking-widest text-gray-500">{label}</p>
            </div>
        );
    };

    return (
        <div className="min-h-screen bg-black text-white font-sans selection:bg-[#ff4d00]/30">
            <Navbar />
            <SEOHead
                title="Authority Checker"
                description="Check any domain's SEO authority, including Domain Rating and Spam Score."
            />
            <main className="pt-32 pb-24 px-6 md:px-12 max-w-6xl mx-auto">
                <AdBanner size="leaderboard" />
                <div className="text-center mb-16">
                    <motion.h1
                        initial={{ opacity: 0, y: 20 }}
                        animate={{ opacity: 1, y: 0 }}
                        className="text-4xl md:text-6xl font-black mb-6 tracking-tightest leading-tight"
                    >
                        Authority <span className="text-[#ff4d00]">Checker.</span>
                    </motion.h1>
                    <p className="text-gray-500 text-lg max-w-2xl mx-auto font-medium">
                        Analyze Domain Rating, Page Authority, and Spam Score for any website in seconds.
                    </p>
                </div>

                <div className="max-w-2xl mx-auto mb-16">
                    <form onSubmit={handleCheck} className="relative group">
                        <div className="absolute -inset-0.5 bg-gradient-to-r from-[#ff4d00] to-orange-600 rounded-2xl opacity-20 group-hover:opacity-40 blur transition duration-500" />
                        <div className="relative flex bg-[#0a0a0a] border border-white/5 rounded-2xl p-2 gap-2">
                            <input
                                type="url"
                                value={url}
                                onChange={(e) => setUrl(e.target.value)}
                                placeholder="https://example.com"
                                className="flex-grow bg-transparent border-none text-white px-6 py-4 focus:outline-none font-bold placeholder-gray-700"
                                required
                            />
                            <button
                                type="submit"
                                disabled={loading}
                                className="bg-[#ff4d00] text-white px-8 py-4 rounded-xl font-black uppercase tracking-widest hover:brightness-110 transition-all disabled:opacity-50"
                            >
                                {loading ? 'Analyzing...' : 'Check'}
                            </button>
                        </div>
                    </form>
                </div>

                <AdBanner size="leaderboard" className="mt-8 mb-4" />

                <AnimatePresence>
                    {result && !loading && (
                        <motion.div
                            initial={{ opacity: 0, scale: 0.95 }}
                            animate={{ opacity: 1, scale: 1 }}
                            className="max-w-4xl mx-auto"
                        >
                            <div className="modrinth-card p-12 border-white/5 relative overflow-hidden">
                                {/* Subtle Background Elements */}
                                <div className="absolute top-0 right-0 w-64 h-64 bg-[#ff4d00]/5 rounded-full blur-[100px] -translate-y-1/2 translate-x-1/2" />

                                <div className="relative z-10 flex flex-col md:flex-row items-center justify-between gap-12 text-center md:text-left">
                                    <div className="flex-grow">
                                        <div className="flex items-center gap-3 mb-4 justify-center md:justify-start">
                                            <span className="text-[10px] font-black uppercase tracking-widest bg-[#ff4d00]/10 text-[#ff4d00] px-3 py-1 rounded-full">Report Ready</span>
                                            <span className="text-xs text-gray-500 font-bold">{result.url}</span>
                                        </div>
                                        <div className="flex justify-between items-start mb-8">
                                            <h2 className="text-3xl font-black text-white tracking-tight">Domain Health Snapshot</h2>
                                            <button
                                                onClick={handleCopyReport}
                                                className="text-[10px] font-black top-2 relative uppercase tracking-widest text-[#ff4d00] hover:text-white border border-[#ff4d00]/30 px-3 py-1.5 rounded-lg hover:bg-[#ff4d00]/10 transition-all"
                                            >
                                                {copied ? '✅ Copied' : '📋 Copy Report'}
                                            </button>
                                        </div>

                                        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                                            <div className="bg-white/5 border border-white/10 p-4 rounded-xl">
                                                <p className="text-[10px] font-black uppercase tracking-widest text-gray-500 mb-1">Total Backlinks</p>
                                                <p className="text-xl font-black text-white">{result.backlinksCount?.toLocaleString()}</p>
                                            </div>
                                            <div className="bg-white/5 border border-white/10 p-4 rounded-xl">
                                                <p className="text-[10px] font-black uppercase tracking-widest text-gray-500 mb-1">Referring Domains</p>
                                                <p className="text-xl font-black text-white">{result.referringDomains?.toLocaleString()}</p>
                                            </div>
                                        </div>
                                    </div>

                                    <div className="flex flex-wrap justify-center gap-10">
                                        <ScoreRing score={result.domainRating} label="Domain Rating" color="#ff4d00" />
                                        <ScoreRing score={result.pageAuthority} label="Page Authority" color="#3b82f6" />
                                        <div className="flex flex-col items-center">
                                            <div className="w-24 h-24 mb-4 flex items-center justify-center rounded-full bg-white/5 border border-white/10 relative">
                                                <span className={`text-2xl font-black ${parseInt(result.spamScore) > 10 ? 'text-red-500' : 'text-green-500'}`}>
                                                    {result.spamScore}
                                                </span>
                                            </div>
                                            <p className="text-[10px] font-black uppercase tracking-widest text-gray-500">Spam Score</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </motion.div>
                    )}
                </AnimatePresence>
            </main>
            <Footer />
        </div>
    );
};

export default AuthorityChecker;
