import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import Navbar from '../../components/Navbar';
import Footer from '../../components/Footer';
import SEOHead from '../../components/SEOHead';
import API_BASE_URL from '../../utils/api';
import AdBanner from '../../components/AdBanner';

const BacklinkMonitor = () => {
    const [domain, setDomain] = useState('');
    const [loading, setLoading] = useState(false);
    const [copied, setCopied] = useState(false);
    const [results, setResults] = useState(null);

    const handleSearch = async (e) => {
        e.preventDefault();
        if (!domain.trim()) return;
        setLoading(true);
        try {
            const res = await fetch(`${API_BASE_URL}/api/backlinks?domain=${encodeURIComponent(domain)}`);
            const data = await res.json();
            setResults(data);
        } catch (error) {
            console.error(error);
            alert("Failed to scan backlinks.");
        } finally {
            setLoading(false);
        }
    };

    const handleCopyReport = () => {
        if (!results) return;
        const list = results.backlinks?.slice(0, 10).map(b => `- ${b.source} (${b.type}): ${b.targetUrl}`).join('\n');
        const text = `🔗 BACKLINK MONITOR REPORT: ${results.domain}\n\n` +
            `Total Backlinks: ${results.backlinks?.length}\n` +
            `Unique Domains: ${[...new Set(results.backlinks?.map(b => b.source))].length}\n\n` +
            `── TOP DISCOVERIES ──\n${list}\n\n` +
            `Generated by Flamerscoal Search Intelligence`;
        navigator.clipboard.writeText(text);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    return (
        <div className="min-h-screen bg-black text-white font-sans selection:bg-[#ff4d00]/30">
            <Navbar />
            <SEOHead
                title="Backlink Monitor"
                description="Scan and track your website's backlink profile and referring domains."
            />
            <main className="pt-32 pb-24 px-6 md:px-12 max-w-6xl mx-auto">
            <AdBanner size="leaderboard" />
                <div className="text-center mb-16">
                    <motion.h1
                        initial={{ opacity: 0, y: 20 }}
                        animate={{ opacity: 1, y: 0 }}
                        className="text-4xl md:text-6xl font-black mb-6 tracking-tightest"
                    >
                        Backlink <span className="text-[#ff4d00]">Monitor.</span>
                    </motion.h1>
                    <p className="text-gray-500 text-lg max-w-2xl mx-auto font-medium">
                        Track your referring domains and discover new link opportunities across the web.
                    </p>
                </div>

                <div className="max-w-2xl mx-auto mb-16">
                    <form onSubmit={handleSearch} className="relative group">
                        <div className="absolute -inset-0.5 bg-gradient-to-r from-[#ff4d00] to-orange-600 rounded-2xl opacity-20 group-hover:opacity-40 blur transition duration-500" />
                        <div className="relative flex bg-[#0a0a0a] border border-white/5 rounded-2xl p-2 gap-2">
                            <input
                                type="text"
                                value={domain}
                                onChange={(e) => setDomain(e.target.value)}
                                placeholder="Enter your domain (e.g. example.com)"
                                className="flex-grow bg-transparent border-none text-white px-6 py-4 focus:outline-none font-bold placeholder-gray-700"
                            />
                            <button
                                type="submit"
                                disabled={loading}
                                className="bg-[#ff4d00] text-white px-8 py-4 rounded-xl font-black uppercase tracking-widest hover:brightness-110 transition-all disabled:opacity-50"
                            >
                                {loading ? 'Scanning...' : 'Scan'}
                            </button>
                        </div>
                    </form>
                </div>

                <AnimatePresence>
                    {results && !loading && (
                        <motion.div
                            initial={{ opacity: 0, y: 20 }}
                            animate={{ opacity: 1, y: 0 }}
                            className="space-y-6"
                        >
                            <div className="flex justify-end">
                                <button
                                    onClick={handleCopyReport}
                                    className="text-[10px] font-black uppercase tracking-widest text-gray-300 hover:text-white border border-white/10 px-4 py-2 rounded-lg hover:bg-[#ff4d00]/5 hover:border-[#ff4d00]/30 transition-all"
                                >
                                    {copied ? '✅ Report Copied' : '📋 Copy Report'}
                                </button>
                            </div>
                            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                                <div className="modrinth-card p-8 text-center border-[#ff4d00]/20">
                                    <p className="text-[10px] font-black uppercase tracking-widest text-gray-500 mb-2">Total Backlinks</p>
                                    <p className="text-5xl font-black text-white">{results.backlinks?.length || 0}</p>
                                </div>
                                <div className="modrinth-card p-8 text-center border-white/5">
                                    <p className="text-[10px] font-black uppercase tracking-widest text-gray-500 mb-2">Unique Domains</p>
                                    <p className="text-5xl font-black text-white">
                                        {[...new Set(results.backlinks?.map(b => b.source))].length}
                                    </p>
                                </div>
                                <div className="modrinth-card p-8 text-center border-white/5">
                                    <p className="text-[10px] font-black uppercase tracking-widest text-gray-500 mb-2">Discovery Pct</p>
                                    <p className="text-5xl font-black text-green-500">100%</p>
                                </div>
                            </div>

                            <div className="modrinth-card overflow-hidden border-white/5">
                                <div className="overflow-x-auto">
                                    <table className="w-full text-left">
                                        <thead>
                                            <tr className="bg-white/5 border-b border-white/10 uppercase tracking-widest text-[10px] font-black text-gray-400">
                                                <th className="px-8 py-6">Source Domain</th>
                                                <th className="px-8 py-6">Link Type</th>
                                                <th className="px-8 py-6">Target URL</th>
                                                <th className="px-8 py-6">Status</th>
                                            </tr>
                                        </thead>
                                        <tbody className="divide-y divide-white/5">
                                            {results.backlinks?.map((link, idx) => (
                                                <tr key={idx} className="hover:bg-white/5 transition-colors group">
                                                    <td className="px-8 py-6">
                                                        <div className="font-black text-white text-sm group-hover:text-[#ff4d00] transition-colors">
                                                            {link.source}
                                                        </div>
                                                    </td>
                                                    <td className="px-8 py-6">
                                                        <span className="text-[10px] font-bold uppercase tracking-wide bg-white/5 border border-white/10 px-3 py-1 rounded-full text-gray-400">
                                                            {link.type}
                                                        </span>
                                                    </td>
                                                    <td className="px-8 py-6">
                                                        <a href={link.targetUrl} target="_blank" rel="noopener noreferrer" className="text-xs text-blue-400 hover:underline">
                                                            {link.targetUrl.substring(0, 40)}...
                                                        </a>
                                                    </td>
                                                    <td className="px-8 py-6">
                                                        <span className="text-[10px] font-black uppercase text-green-500 bg-green-500/10 px-3 py-1 rounded-full">
                                                            {link.status}
                                                        </span>
                                                    </td>
                                                </tr>
                                            ))}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </motion.div>
                    )}
                </AnimatePresence>
            </main>
            <Footer />
        </div>
    );
};

export default BacklinkMonitor;
