import React, { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { Link } from 'react-router-dom';
import Footer from '../../components/Footer';
import AdBanner from '../../components/AdBanner';
import SEOHead from '../../components/SEOHead';
import API_BASE_URL from '../../utils/api';

const KeywordResearch = () => {
    const [query, setQuery] = useState('');
    const [loading, setLoading] = useState(false);
    const [loadingMessage, setLoadingMessage] = useState('');
    const [results, setResults] = useState(null);
    const [copied, setCopied] = useState(false);
    const [competitors, setCompetitors] = useState([]);
    const [filters, setFilters] = useState({
        minVolume: 0,
        maxKD: 100,
        search: ''
    });

    const filteredKeywords = results?.keywords.filter(kw => {
        const matchesSearch = kw.term.toLowerCase().includes(filters.search.toLowerCase());
        const matchesVolume = parseInt(kw.volume.replace(/,/g, '')) >= filters.minVolume;
        const matchesKD = kw.kd <= filters.maxKD;
        return matchesSearch && matchesVolume && matchesKD;
    }) || [];

    const loadingSteps = [
        "🔍 Connecting to search servers...",
        "📊 Analyzing search volume trends...",
        "⚔️ Scouting top competitors...",
        "📉 Calculating keyword difficulty...",
        "🚀 Finalizing your report..."
    ];

    useEffect(() => {
        let interval;
        if (loading) {
            let step = 0;
            setLoadingMessage(loadingSteps[0]);
            interval = setInterval(() => {
                step = (step + 1) % loadingSteps.length;
                setLoadingMessage(loadingSteps[step]);
            }, 800); // Change message every 800ms
        }
        return () => clearInterval(interval);
    }, [loading]);

    const handleCopyReport = () => {
        if (!results) return;
        const kwList = filteredKeywords.slice(0, 10).map(k => `- ${k.term}: ${k.volume} (KD: ${k.kd})`).join('\n');
        const text = `📊 KEYWORD RESEARCH REPORT: "${results.query}"\n\n` +
            `── OVERVIEW ──\n` +
            `Volume: ${results.overview.volume}\n` +
            `Difficulty: ${results.overview.difficulty}\n` +
            `CPC: ${results.overview.cpc}\n` +
            `Paid Difficulty: ${results.overview.paidDifficulty}\n\n` +
            `── TOP VARIATIONS ──\n${kwList}\n\n` +
            `── COMPETITORS ──\n${competitors.map((c, i) => `${i + 1}. ${c.domain}`).join('\n')}\n\n` +
            `Generated by Flamerscoal Search Intelligence`;
        navigator.clipboard.writeText(text);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    const handleSearch = async (e) => {
        e.preventDefault();
        if (!query.trim()) return;

        setLoading(true);
        setResults(null);
        setCompetitors([]);

        try {
            // Parallel Fetch: Keywords + Competitors
            const [kwRes, compRes] = await Promise.all([
                fetch(`${API_BASE_URL}/api/keywords?q=${encodeURIComponent(query)}`),
                fetch(`${API_BASE_URL}/api/competitors?q=${encodeURIComponent(query)}`)
            ]);

            const kwData = await kwRes.json();

            // Handle Competitor Data gracefully
            let compData = { competitors: [] };
            try {
                if (compRes.ok) compData = await compRes.json();
            } catch (err) { console.warn("Competitor fetch failed", err); }

            if (kwData.error) {
                throw new Error(kwData.details || kwData.error);
            }

            setResults(kwData);
            if (compData.competitors) setCompetitors(compData.competitors);

        } catch (error) {
            console.error("API Error:", error);
            alert("Could not fetch keyword data. Make sure the backend server is running.");
        } finally {
            setLoading(false);
        }
    };

    return (
        <div className="min-h-screen bg-black text-gray-200 font-sans selection:bg-purple-500/30">
            <SEOHead
                title="Keyword Research"
                description="Find high-potential keywords with search volume, difficulty, and CPC data."
            />
            {/* Subtle Gradient Mesh - Toned Down */}
            <div className="fixed inset-0 z-0 pointer-events-none">
                <div className="absolute top-[-20%] left-[-10%] w-[50%] h-[50%] bg-purple-900/20 rounded-full blur-[150px]" />
                <div className="absolute bottom-[-20%] right-[-10%] w-[50%] h-[50%] bg-blue-900/20 rounded-full blur-[150px]" />
            </div>



            <main className="relative z-10 p-6 max-w-7xl mx-auto min-h-[85vh]">
                <div className="max-w-4xl mx-auto mb-12 text-center pt-8">
                    <motion.h1
                        initial={{ opacity: 0, y: 10 }}
                        animate={{ opacity: 1, y: 0 }}
                        className="text-3xl md:text-5xl font-bold mb-4 text-white tracking-tight"
                    >
                        Keyword Research
                    </motion.h1>
                    <motion.p
                        initial={{ opacity: 0 }}
                        animate={{ opacity: 1 }}
                        transition={{ delay: 0.1 }}
                        className="text-gray-500 text-lg"
                    >
                        Analyze search volume, competition, and trends in seconds.
                    </motion.p>
                </div>

                {/* Minimalist Search Interface */}
                <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: 0.2 }}
                    className="max-w-3xl mx-auto mb-16"
                >
                    <form onSubmit={handleSearch} className="relative group">
                        <div className="absolute -inset-1 bg-gradient-to-r from-purple-600 to-blue-600 rounded-xl opacity-20 group-hover:opacity-40 blur transition duration-500"></div>
                        <div className="relative flex items-center bg-gray-900 border border-gray-800 rounded-xl shadow-2xl p-2">
                            <div className="pl-4 text-gray-500">
                                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="11" cy="11" r="8"></circle><line x1="21" y1="21" x2="16.65" y2="16.65"></line></svg>
                            </div>
                            <input
                                type="text"
                                value={query}
                                onChange={(e) => setQuery(e.target.value)}
                                placeholder="Enter a keyword (e.g. 'best gaming laptops')"
                                className="w-full bg-transparent border-none text-white px-4 py-3 focus:ring-0 text-lg placeholder-gray-600"
                                required
                            />
                            <div className="hidden md:block h-8 w-px bg-gray-800 mx-2"></div>
                            <select className="hidden md:block bg-transparent text-gray-400 text-sm font-medium border-none focus:ring-0 cursor-pointer hover:text-white transition-colors">
                                <option>United States</option>
                                <option>United Kingdom</option>
                                <option>India</option>
                                <option>Australia</option>
                            </select>
                            <button
                                type="submit"
                                disabled={loading}
                                className={`ml-2 px-6 py-2.5 font-semibold rounded-lg transition-all disabled:cursor-not-allowed whitespace-nowrap min-w-[140px] flex justify-center items-center ${loading ? 'bg-gray-800 text-purple-400 border border-purple-500/30' : 'bg-white text-black hover:bg-gray-200'}`}
                            >
                                {loading ? (
                                    <div className="flex items-center gap-2">
                                        <div className="w-4 h-4 border-2 border-purple-500 border-t-transparent rounded-full animate-spin"></div>
                                        <span className="text-xs animate-pulse">{loadingMessage}</span>
                                    </div>
                                ) : 'Search'}
                            </button>
                        </div>
                    </form>
                </motion.div>

                <AdBanner size="leaderboard" className="mt-8 mb-4" />

                {/* Results Section */}
                {results && !loading && (
                    <motion.div
                        initial={{ opacity: 0 }}
                        animate={{ opacity: 1 }}
                        transition={{ staggerChildren: 0.1 }}
                        className="space-y-8"
                    >
                        {/* Metrics Overview */}
                        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                            <MetricCard label="Search Volume" value={results.overview.volume} sub="Monthly Searches" />
                            <MetricCard label="Difficulty" value={results.overview.difficulty} sub="SEO Difficulty" />
                            <MetricCard label="CPC" value={results.overview.cpc} sub="Cost Per Click" />
                            <MetricCard label="Paid Difficulty" value={results.overview.paidDifficulty} sub="Competition Level" />
                        </div>

                        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
                            {/* Main Data Table */}
                            <div className="lg:col-span-2 space-y-4">
                                <div className="flex flex-col md:flex-row justify-between items-end md:items-center gap-4">
                                    <h3 className="text-xl font-semibold text-white">Keyword Variations ({filteredKeywords.length})</h3>
                                    <div className="flex gap-2">
                                        <button
                                            onClick={handleCopyReport}
                                            className="text-sm text-gray-300 hover:text-white transition-all border border-gray-800 px-4 py-1.5 rounded-lg hover:border-[#ff4d00]/30 hover:bg-[#ff4d00]/5 font-bold"
                                        >
                                            {copied ? '✅ Copied' : '📋 Copy Report'}
                                        </button>
                                        <button className="text-sm text-gray-500 hover:text-white transition-colors border border-gray-800 px-3 py-1.5 rounded-lg hover:border-gray-600">Export CSV</button>
                                    </div>
                                </div>

                                {/* Filters Bar */}
                                <div className="bg-gray-900/50 border border-gray-800 rounded-xl p-4 flex flex-wrap gap-4 items-center">
                                    <div className="flex-1 min-w-[200px]">
                                        <label className="text-xs text-gray-500 uppercase font-bold mb-1 block">Search Result</label>
                                        <input
                                            type="text"
                                            placeholder="Filter keywords..."
                                            value={filters.search}
                                            onChange={(e) => setFilters({ ...filters, search: e.target.value })}
                                            className="w-full bg-gray-900 border border-gray-700 rounded-lg px-3 py-2 text-sm text-white focus:ring-1 focus:ring-purple-500 outline-none"
                                        />
                                    </div>
                                    <div className="w-[120px]">
                                        <label className="text-xs text-gray-500 uppercase font-bold mb-1 block">Min Volume</label>
                                        <input
                                            type="number"
                                            placeholder="0"
                                            value={filters.minVolume}
                                            onChange={(e) => setFilters({ ...filters, minVolume: parseInt(e.target.value) || 0 })}
                                            className="w-full bg-gray-900 border border-gray-700 rounded-lg px-3 py-2 text-sm text-white focus:ring-1 focus:ring-purple-500 outline-none"
                                        />
                                    </div>
                                    <div className="w-[120px]">
                                        <label className="text-xs text-gray-500 uppercase font-bold mb-1 block">Max KD</label>
                                        <input
                                            type="number"
                                            placeholder="100"
                                            min="0"
                                            max="100"
                                            value={filters.maxKD}
                                            onChange={(e) => setFilters({ ...filters, maxKD: parseInt(e.target.value) || 100 })}
                                            className="w-full bg-gray-900 border border-gray-700 rounded-lg px-3 py-2 text-sm text-white focus:ring-1 focus:ring-purple-500 outline-none"
                                        />
                                    </div>
                                </div>

                                <div className="bg-gray-900 border border-gray-800 rounded-xl overflow-hidden shadow-sm">
                                    <div className="overflow-x-auto">
                                        <table className="w-full text-left">
                                            <thead>
                                                <tr className="border-b border-gray-800 bg-gray-900/50 text-xs uppercase text-gray-500 tracking-wider">
                                                    <th className="p-4 font-medium">Keyword</th>
                                                    <th className="p-4 font-medium w-32">Volume</th>
                                                    <th className="p-4 font-medium w-32">Trend</th>
                                                    <th className="p-4 font-medium w-24">KD</th>
                                                    <th className="p-4 font-medium w-24">CPC</th>
                                                </tr>
                                            </thead>
                                            <tbody className="divide-y divide-gray-800 text-sm">
                                                {filteredKeywords.length > 0 ? (
                                                    filteredKeywords.map((kw, i) => (
                                                        <tr key={i} className="hover:bg-gray-800/40 transition-colors group">
                                                            <td className="p-4 font-medium text-gray-200">{kw.term}</td>
                                                            <td className="p-4 text-gray-400">{kw.volume}</td>
                                                            <td className="p-4">
                                                                <div className="flex items-end gap-0.5 h-6 opacity-60">
                                                                    {kw.trend.map((h, j) => (
                                                                        <div key={j} style={{ height: `${h}%` }} className="w-1.5 bg-purple-500 rounded-t-[1px]" />
                                                                    ))}
                                                                </div>
                                                            </td>
                                                            <td className="p-4">
                                                                <span className={`inline-block w-8 text-center py-0.5 rounded text-xs font-bold ${getDifficultyClass(kw.kd)}`}>
                                                                    {kw.kd}
                                                                </span>
                                                            </td>
                                                            <td className="p-4 text-gray-400">{kw.cpc}</td>
                                                        </tr>
                                                    ))
                                                ) : (
                                                    <tr>
                                                        <td colSpan="5" className="p-8 text-center text-gray-500">
                                                            No keywords match your filters.
                                                        </td>
                                                    </tr>
                                                )}
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>

                            {/* Sidebar: Competitors */}
                            <div className="space-y-6">
                                <div className="bg-gray-900 border border-gray-800 rounded-xl p-5 shadow-sm">
                                    <h3 className="text-lg font-semibold text-white mb-4 flex items-center gap-2">
                                        Top Competitors
                                    </h3>

                                    {competitors.length > 0 ? (
                                        <ul className="space-y-3">
                                            {competitors.map((comp, idx) => (
                                                <li key={idx} className="flex items-center gap-3 p-2 rounded-lg hover:bg-gray-800/50 transition-colors">
                                                    <span className="text-gray-600 text-sm font-mono w-4 text-right">{idx + 1}.</span>
                                                    <div className="flex-1">
                                                        <a
                                                            href={`https://${comp.domain}`}
                                                            target="_blank"
                                                            rel="noopener noreferrer"
                                                            className="text-blue-400 hover:text-blue-300 font-medium text-sm block truncate"
                                                        >
                                                            {comp.domain}
                                                        </a>
                                                    </div>
                                                </li>
                                            ))}
                                        </ul>
                                    ) : (
                                        <div className="text-center py-8 text-gray-500 text-sm italic">
                                            Analyzing SERP data...
                                        </div>
                                    )}
                                </div>

                                <div className="bg-gradient-to-br from-purple-900/10 to-blue-900/10 border border-purple-500/10 rounded-xl p-5">
                                    <h3 className="font-semibold text-white mb-1">💡 Opportunity</h3>
                                    <p className="text-sm text-gray-400 mb-3">
                                        Target long-tail keywords with volume under {results.overview.volume} to outrank these competitors.
                                    </p>
                                </div>

                                {/* Ad Space - Sidebar: Triple 300x250 */}
                                <div className="space-y-4">
                                    <AdBanner size="rectangle" />
                                    <AdBanner size="rectangle" />
                                    <AdBanner size="rectangle" />
                                </div>
                            </div>
                        </div>
                    </motion.div>
                )}
            </main>

            {/* Ad Space - Bottom */}
            <div className="max-w-7xl mx-auto px-6 mb-12">
                <AdContainer slot="keyword_bottom" className="h-[90px] w-full bg-gray-900/30 rounded-xl" />
            </div>

            {/* Discover More Tools Section */}
            <section className="py-20 border-t border-gray-900 bg-black">
                <div className="max-w-7xl mx-auto px-6">
                    <h2 className="text-2xl font-bold text-white mb-8 text-center">Discover More Tools</h2>
                    <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                        <Link to="/tools/keyword-research" className="block group">
                            <div className="bg-gray-900 border border-purple-500/30 p-6 rounded-xl h-full hover:bg-gray-800 transition-colors">
                                <div className="text-3xl mb-3">🔍</div>
                                <h3 className="font-bold text-white mb-1">Keyword Research</h3>
                                <p className="text-sm text-gray-400">Find profitable keywords instantly.</p>
                            </div>
                        </Link>
                        <div className="bg-gray-900/50 border border-gray-800 p-6 rounded-xl h-full opacity-60 cursor-not-allowed">
                            <div className="text-3xl mb-3">⚡</div>
                            <h3 className="font-bold text-gray-300 mb-1">Speed Analyzer</h3>
                            <p className="text-sm text-gray-500">Analyze site performance (Coming Soon).</p>
                        </div>
                        <div className="bg-gray-900/50 border border-gray-800 p-6 rounded-xl h-full opacity-60 cursor-not-allowed">
                            <div className="text-3xl mb-3">🔗</div>
                            <h3 className="font-bold text-gray-300 mb-1">Backlink Checker</h3>
                            <p className="text-sm text-gray-500">Monitor your link profile (Coming Soon).</p>
                        </div>
                    </div>
                </div>
            </section>

            <Footer />
        </div>
    );
};

// Simplified Metric Card
const MetricCard = ({ label, value, sub }) => (
    <div className="bg-gray-900 border border-gray-800 p-5 rounded-xl hover:border-gray-700 transition-colors">
        <p className="text-gray-500 text-xs uppercase tracking-wider font-semibold mb-1">{label}</p>
        <p className="text-2xl font-bold text-white mb-1">{value}</p>
        <p className="text-gray-400 text-xs">{sub}</p>
    </div>
);

// Cleaner Difficulty Badges
const getDifficultyClass = (score) => {
    if (score < 30) return "text-green-400 bg-green-400/10";
    if (score < 60) return "text-yellow-400 bg-yellow-400/10";
    return "text-red-400 bg-red-400/10";
};

export default KeywordResearch;
